### ISSUE TITLE
Reddit Scraper

### ISSUE THREAD

**Issue by Swinks95** [KevHg/reddit-sentiment#4]
Hi there,

I saw your very nice reddit-sentiment code and I am thinking of using it in order to perform a measurement to see if sentiment on political related subreddits have become more positive or negative over the years. I am fairly new to this field and how to implement everything in Python so I had a question. I am going to use MongoDB to connect to reddit and the subreddits I will need will be available. However, can I still use your scraping script and connect it to MongoDB to collect the comments of the subreddits in order to make the dataset?

THank you in advance!

**Comment by KevHg** [comment]
Feel free to use it :+1:
